spring:
  datasource:
    url: jdbc:postgresql:pharmagator
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate


pharmagator:
  data-providers:
    apteka-ds:
      url: https://api-int.apteka-ds.com.ua/api/v1
      category-fetch-url: /category-menu
      category-path: /cat-prods-by-page
      pharmacy-name: apteka-ds
      limiting-pages: 1
      limiting-products-per-page: 50
    pharmacy-anc:
      url: https://anc.ua/productbrowser/v2/ua
      category-fetch-url: /categories
      page-size: 10
      pharmacy-name: pharmacy-anc
    apteka-liki24:
      url: https://liki24.com/vnext/api/catalogue/8000001/products
      initial-page-index: 1
      pharmacy-name: apteka-liki24
    apteka-rozetka:
      url: https://xl-catalog-api.rozetka.com.ua/v4
      product-ids-fetch-url: /goods/get
      products-fetch-url: /goods/getDetails
      sell-status: available
      category-id: !!str 4628621
      medicament-category-id: !!str 4628712
      pharmacy-name: apteka-rozetka
      page-limit: 5
